// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An API for 42 tutors.",
    "title": "42 Tutors API",
    "contact": {},
    "version": "0.0.1"
  },
  "paths": {
    "/auth/callback": {
      "get": {
        "security": [],
        "description": "Retrieve token from 42 API.",
        "tags": [
          "Authentication"
        ],
        "summary": "Return user token",
        "operationId": "callback",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      }
    },
    "/events": {
      "get": {
        "description": "List all events.",
        "tags": [
          "Event"
        ],
        "summary": "List events",
        "operationId": "listEvent",
        "parameters": [
          {
            "type": "string",
            "description": "Day filter.",
            "name": "day",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Week filter.",
            "name": "week",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Month filter.",
            "name": "month",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Event"
              }
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "post": {
        "description": "Create a new event.",
        "tags": [
          "Event"
        ],
        "summary": "Create event",
        "operationId": "createEvent",
        "parameters": [
          {
            "description": "Event to create.",
            "name": "event",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Event"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      }
    },
    "/events/{id}": {
      "get": {
        "description": "Read an event by ID.",
        "tags": [
          "Event"
        ],
        "summary": "Read event",
        "operationId": "readEvent",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "put": {
        "description": "Update an event by ID.",
        "tags": [
          "Event"
        ],
        "summary": "Update event",
        "operationId": "updateEvent",
        "parameters": [
          {
            "description": "Event to update.",
            "name": "event",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Event"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "delete": {
        "description": "Delete an event by ID.",
        "tags": [
          "Event"
        ],
        "summary": "Delete event",
        "operationId": "deleteEvent",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "Event ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/events/{id}/users": {
      "get": {
        "description": "List users subscribed to an event.",
        "tags": [
          "Event"
        ],
        "summary": "List event users",
        "operationId": "listEventUsers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "Event ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/login": {
      "get": {
        "security": [],
        "description": "Login to 42 API with OAuth 2.0.",
        "tags": [
          "Authentication"
        ],
        "summary": "Login user",
        "operationId": "login",
        "responses": {
          "302": {
            "description": "Found"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      }
    },
    "/users": {
      "get": {
        "description": "List all users.",
        "tags": [
          "User"
        ],
        "summary": "List users",
        "operationId": "listUser",
        "parameters": [
          {
            "type": "boolean",
            "description": "List all tutors.",
            "name": "tutor",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "post": {
        "description": "Create a new user.",
        "tags": [
          "User"
        ],
        "summary": "Create user",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "User to create.",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "description": "Read the authenticated user.",
        "tags": [
          "User"
        ],
        "summary": "Read authenticated user",
        "operationId": "readMe",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "put": {
        "description": "Update the authenticated user.",
        "tags": [
          "User"
        ],
        "summary": "Update authenticated user",
        "operationId": "updateMe",
        "parameters": [
          {
            "description": "User to update.",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "delete": {
        "description": "Delete the authenticated user.",
        "tags": [
          "User"
        ],
        "summary": "Delete authenticated user",
        "operationId": "deleteMe",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      }
    },
    "/users/me/events": {
      "get": {
        "description": "List the authenticated user's subscribed events.",
        "tags": [
          "User"
        ],
        "summary": "List authenticated user events",
        "operationId": "listMeEvents",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Event"
              }
            }
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      }
    },
    "/users/me/events/{id}": {
      "post": {
        "description": "Subscribe an authenticated user to an event.",
        "tags": [
          "User"
        ],
        "summary": "Subscribe authenticated user",
        "operationId": "subscribeMe",
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "type": "string",
              "example": "Done"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "delete": {
        "description": "Unsubscribe an authenticated user to an event.",
        "tags": [
          "User"
        ],
        "summary": "Unsubscribe authenticated user",
        "operationId": "unsubscribeMe",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "Event ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{id}": {
      "get": {
        "description": "Read an user by ID.",
        "tags": [
          "User"
        ],
        "summary": "Read user",
        "operationId": "readUser",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "put": {
        "description": "Update an user by ID.",
        "tags": [
          "User"
        ],
        "summary": "Update user",
        "operationId": "updateUser",
        "parameters": [
          {
            "description": "User to update.",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "delete": {
        "description": "Delete an user by ID.",
        "tags": [
          "User"
        ],
        "summary": "Delete user",
        "operationId": "deleteUser",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "User ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{id}/events": {
      "get": {
        "description": "List user's subscribed events.",
        "tags": [
          "User"
        ],
        "summary": "List user events",
        "operationId": "listUserEvents",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Event"
              }
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "User ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{userId}/events/{eventId}": {
      "post": {
        "description": "Subscribe a user to an event.",
        "tags": [
          "User"
        ],
        "summary": "Subscribe user",
        "operationId": "subscribeUser",
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "type": "string",
              "example": "Done"
            }
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "delete": {
        "description": "Unsubscribe a user to an event.",
        "tags": [
          "User"
        ],
        "summary": "Unsubscribe user",
        "operationId": "unsubscribeUser",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "$ref": "#/responses/400"
          },
          "404": {
            "$ref": "#/responses/404"
          },
          "500": {
            "$ref": "#/responses/500"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "User ID.",
          "name": "userId",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "description": "Event ID.",
          "name": "eventId",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "example": 500
        },
        "message": {
          "type": "string",
          "example": "Internal Server Error"
        }
      }
    },
    "Event": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "readOnly": true,
          "example": "2022-02-15T09:00:00Z"
        },
        "description": {
          "type": "string",
          "format": "string",
          "example": "Exam Alone in the Dark - Exam Rank 2/3/4/5/6"
        },
        "endAt": {
          "type": "string",
          "format": "date-time",
          "example": "2022-02-15T13:00:00+01:00"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "123e4567-e89b-12d3-a456-426614174000"
        },
        "name": {
          "type": "string",
          "format": "string",
          "minLength": 1,
          "example": "Exam Stud"
        },
        "startAt": {
          "type": "string",
          "format": "date-time",
          "example": "2022-02-15T10:00:00+01:00"
        },
        "tutorsRequired": {
          "type": "integer",
          "format": "int64",
          "example": 3
        },
        "type": {
          "type": "string",
          "format": "string",
          "minLength": 1,
          "example": "Exam"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        },
        "walletsReward": {
          "type": "integer",
          "format": "int64",
          "example": 200
        }
      },
      "x-go-type": {
        "hints": {
          "kind": "object"
        },
        "import": {
          "package": "github.com/gmarcha/ent-goswagger-app/internal/ent"
        },
        "type": "Event"
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "adminScope": {
          "type": "boolean",
          "example": false
        },
        "calendarScope": {
          "type": "boolean",
          "example": true
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Event"
          }
        },
        "firstName": {
          "type": "string",
          "format": "string",
          "example": "Go"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "123e4567-e89b-12d3-a456-426614174000"
        },
        "imageUrl": {
          "type": "string",
          "format": "uri",
          "example": "https://api.intra.42.fr/gamarcha/img"
        },
        "lastName": {
          "type": "string",
          "format": "string",
          "example": "Swagger"
        },
        "login": {
          "type": "string",
          "format": "string",
          "minLength": 2,
          "example": "gamarcha"
        }
      },
      "x-go-type": {
        "hints": {
          "kind": "object"
        },
        "import": {
          "package": "github.com/gmarcha/ent-goswagger-app/internal/ent"
        },
        "type": "User"
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "responses": {
    "400": {
      "description": "Bad request",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "401": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "403": {
      "description": "Forbidden",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "404": {
      "description": "Not Found",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "500": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  },
  "securityDefinitions": {
    "OauthSecurity": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://api.intra.42.fr/oauth/authorize",
      "tokenUrl": "https://api.intra.42.fr/oauth/token",
      "scopes": {
        "tutor": "Tutor scope"
      }
    }
  },
  "security": [
    {
      "OauthSecurity": [
        "tutor"
      ]
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "An API for 42 tutors.",
    "title": "42 Tutors API",
    "contact": {},
    "version": "0.0.1"
  },
  "paths": {
    "/auth/callback": {
      "get": {
        "security": [],
        "description": "Retrieve token from 42 API.",
        "tags": [
          "Authentication"
        ],
        "summary": "Return user token",
        "operationId": "callback",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/events": {
      "get": {
        "description": "List all events.",
        "tags": [
          "Event"
        ],
        "summary": "List events",
        "operationId": "listEvent",
        "parameters": [
          {
            "type": "string",
            "description": "Day filter.",
            "name": "day",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Week filter.",
            "name": "week",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Month filter.",
            "name": "month",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Event"
              }
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "Create a new event.",
        "tags": [
          "Event"
        ],
        "summary": "Create event",
        "operationId": "createEvent",
        "parameters": [
          {
            "description": "Event to create.",
            "name": "event",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Event"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/events/{id}": {
      "get": {
        "description": "Read an event by ID.",
        "tags": [
          "Event"
        ],
        "summary": "Read event",
        "operationId": "readEvent",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "description": "Update an event by ID.",
        "tags": [
          "Event"
        ],
        "summary": "Update event",
        "operationId": "updateEvent",
        "parameters": [
          {
            "description": "Event to update.",
            "name": "event",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Event"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Event"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Delete an event by ID.",
        "tags": [
          "Event"
        ],
        "summary": "Delete event",
        "operationId": "deleteEvent",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "Event ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/events/{id}/users": {
      "get": {
        "description": "List users subscribed to an event.",
        "tags": [
          "Event"
        ],
        "summary": "List event users",
        "operationId": "listEventUsers",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "Event ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/login": {
      "get": {
        "security": [],
        "description": "Login to 42 API with OAuth 2.0.",
        "tags": [
          "Authentication"
        ],
        "summary": "Login user",
        "operationId": "login",
        "responses": {
          "302": {
            "description": "Found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "description": "List all users.",
        "tags": [
          "User"
        ],
        "summary": "List users",
        "operationId": "listUser",
        "parameters": [
          {
            "type": "boolean",
            "description": "List all tutors.",
            "name": "tutor",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "Create a new user.",
        "tags": [
          "User"
        ],
        "summary": "Create user",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "User to create.",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "description": "Read the authenticated user.",
        "tags": [
          "User"
        ],
        "summary": "Read authenticated user",
        "operationId": "readMe",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "description": "Update the authenticated user.",
        "tags": [
          "User"
        ],
        "summary": "Update authenticated user",
        "operationId": "updateMe",
        "parameters": [
          {
            "description": "User to update.",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Delete the authenticated user.",
        "tags": [
          "User"
        ],
        "summary": "Delete authenticated user",
        "operationId": "deleteMe",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/users/me/events": {
      "get": {
        "description": "List the authenticated user's subscribed events.",
        "tags": [
          "User"
        ],
        "summary": "List authenticated user events",
        "operationId": "listMeEvents",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Event"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/users/me/events/{id}": {
      "post": {
        "description": "Subscribe an authenticated user to an event.",
        "tags": [
          "User"
        ],
        "summary": "Subscribe authenticated user",
        "operationId": "subscribeMe",
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "type": "string",
              "example": "Done"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Unsubscribe an authenticated user to an event.",
        "tags": [
          "User"
        ],
        "summary": "Unsubscribe authenticated user",
        "operationId": "unsubscribeMe",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "Event ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{id}": {
      "get": {
        "description": "Read an user by ID.",
        "tags": [
          "User"
        ],
        "summary": "Read user",
        "operationId": "readUser",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "description": "Update an user by ID.",
        "tags": [
          "User"
        ],
        "summary": "Update user",
        "operationId": "updateUser",
        "parameters": [
          {
            "description": "User to update.",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Delete an user by ID.",
        "tags": [
          "User"
        ],
        "summary": "Delete user",
        "operationId": "deleteUser",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "User ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{id}/events": {
      "get": {
        "description": "List user's subscribed events.",
        "tags": [
          "User"
        ],
        "summary": "List user events",
        "operationId": "listUserEvents",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Event"
              }
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "User ID.",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/users/{userId}/events/{eventId}": {
      "post": {
        "description": "Subscribe a user to an event.",
        "tags": [
          "User"
        ],
        "summary": "Subscribe user",
        "operationId": "subscribeUser",
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "type": "string",
              "example": "Done"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "Unsubscribe a user to an event.",
        "tags": [
          "User"
        ],
        "summary": "Unsubscribe user",
        "operationId": "unsubscribeUser",
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "User ID.",
          "name": "userId",
          "in": "path",
          "required": true
        },
        {
          "type": "string",
          "description": "Event ID.",
          "name": "eventId",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "example": 500
        },
        "message": {
          "type": "string",
          "example": "Internal Server Error"
        }
      }
    },
    "Event": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "readOnly": true,
          "example": "2022-02-15T09:00:00Z"
        },
        "description": {
          "type": "string",
          "format": "string",
          "example": "Exam Alone in the Dark - Exam Rank 2/3/4/5/6"
        },
        "endAt": {
          "type": "string",
          "format": "date-time",
          "example": "2022-02-15T13:00:00+01:00"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "123e4567-e89b-12d3-a456-426614174000"
        },
        "name": {
          "type": "string",
          "format": "string",
          "minLength": 1,
          "example": "Exam Stud"
        },
        "startAt": {
          "type": "string",
          "format": "date-time",
          "example": "2022-02-15T10:00:00+01:00"
        },
        "tutorsRequired": {
          "type": "integer",
          "format": "int64",
          "example": 3
        },
        "type": {
          "type": "string",
          "format": "string",
          "minLength": 1,
          "example": "Exam"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        },
        "walletsReward": {
          "type": "integer",
          "format": "int64",
          "example": 200
        }
      },
      "x-go-type": {
        "hints": {
          "kind": "object"
        },
        "import": {
          "package": "github.com/gmarcha/ent-goswagger-app/internal/ent"
        },
        "type": "Event"
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "adminScope": {
          "type": "boolean",
          "example": false
        },
        "calendarScope": {
          "type": "boolean",
          "example": true
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Event"
          }
        },
        "firstName": {
          "type": "string",
          "format": "string",
          "example": "Go"
        },
        "id": {
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "123e4567-e89b-12d3-a456-426614174000"
        },
        "imageUrl": {
          "type": "string",
          "format": "uri",
          "example": "https://api.intra.42.fr/gamarcha/img"
        },
        "lastName": {
          "type": "string",
          "format": "string",
          "example": "Swagger"
        },
        "login": {
          "type": "string",
          "format": "string",
          "minLength": 2,
          "example": "gamarcha"
        }
      },
      "x-go-type": {
        "hints": {
          "kind": "object"
        },
        "import": {
          "package": "github.com/gmarcha/ent-goswagger-app/internal/ent"
        },
        "type": "User"
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "responses": {
    "400": {
      "description": "Bad request",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "401": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "403": {
      "description": "Forbidden",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "404": {
      "description": "Not Found",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "500": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  },
  "securityDefinitions": {
    "OauthSecurity": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://api.intra.42.fr/oauth/authorize",
      "tokenUrl": "https://api.intra.42.fr/oauth/token",
      "scopes": {
        "tutor": "Tutor scope"
      }
    }
  },
  "security": [
    {
      "OauthSecurity": [
        "tutor"
      ]
    }
  ]
}`))
}
