// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateEventHandlerFunc turns a function with the right signature into a create event handler
type CreateEventHandlerFunc func(CreateEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateEventHandlerFunc) Handle(params CreateEventParams) middleware.Responder {
	return fn(params)
}

// CreateEventHandler interface for that can handle valid create event params
type CreateEventHandler interface {
	Handle(CreateEventParams) middleware.Responder
}

// NewCreateEvent creates a new http.Handler for the create event operation
func NewCreateEvent(ctx *middleware.Context, handler CreateEventHandler) *CreateEvent {
	return &CreateEvent{Context: ctx, Handler: handler}
}

/* CreateEvent swagger:route POST /events Event createEvent

Create event

Create a new event.

*/
type CreateEvent struct {
	Context *middleware.Context
	Handler CreateEventHandler
}

func (o *CreateEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
