version: "3.9"

services:
  reverse-proxy:
    image: "traefik:v2.4"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=default"
      # - "--providers.file.directory=/etc/traefik"
      # - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.leresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.leresolver.acme.email=gamarcha@student.42.fr"
      - "--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
      # - ./traefik/config.yaml:/etc/traefik/config.yaml:ro
      # - ./traefik/certs:/etc/certs:ro
    ports:
      - "8880:80"
      - "8443:443"
      - "8080:8080"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    entrypoint: >
      /bin/sh -c "
      echo $${POSTGRES_HOST}:$${POSTGRES_PORT}:$${POSTGRES_DB}:$${POSTGRES_USER}:$${POSTGRES_PASSWORD} > /tmp/pgpass;
      chmod 600 /tmp/pgpass;
      /entrypoint.sh
      "
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED}
    restart: "unless-stopped"
    depends_on:
      - postgres

  goswagger:
    ports: []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goswagger.rule=Host(`tutor.localhost`) && PathPrefix(`/api/`)"
      - "traefik.http.services.goswagger.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.pathstrip.stripprefix.prefixes=/api"
      - "traefik.http.routers.goswagger.middlewares=pathstrip@docker"
      - "traefik.http.routers.goswagger.entrypoints=websecure"
      - "traefik.http.routers.goswagger.tls=true"
      - "traefik.http.routers.goswagger.tls.certresolver=leresolver"

  client:
    image: node:16-alpine
    working_dir: /app
    entrypoint: |
      /bin/sh -c "
        yarn dev --dotenv ../env/.env
      "
    volumes:
      - ../../nuxt-app:/app
      - ./.env.stag:/env/.env
    ports: []
    environment:
      CLIENT_HOST: ${CLIENT_HOST}
      CLIENT_PORT: ${CLIENT_PORT}
      API_CLIENT_ID: ${API_CLIENT_ID}
      API_AUTH_URL: ${API_AUTH_URL}
      API_CALLBACK_URL: ${API_CALLBACK_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`tutor.localhost`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=leresolver"
    restart: unless-stopped

volumes:
  traefik-certificates:
  pgadmin-volume:
