version: "3.9"

services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
    env_file:
      - .env
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    entrypoint: >
      /bin/sh -c "
      echo $${POSTGRES_HOST}:$${POSTGRES_PORT}:$${POSTGRES_DB}:$${POSTGRES_USER}:$${POSTGRES_PASSWORD} > /tmp/pgpass;
      chmod 600 /tmp/pgpass;
      /entrypoint.sh
      "
  goswagger:
    build:
      context: ../
      dockerfile: ./config/Dockerfile
    image: goswagger
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - module-volume:/go/pkg/mod/cache/download
      - build-volume:/root/.cache/go-build

volumes:
  postgres-volume:
  pgadmin-volume:
  module-volume:
  build-volume:
    # https://pkg.go.dev/cmd/go#hdr-Build_and_test_caching
