// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gamarcha/ent-goswagger-app/goswagger/models"
)

// GetLoginFoundCode is the HTTP code returned for type GetLoginFound
const GetLoginFoundCode int = 302

/*GetLoginFound Found

swagger:response getLoginFound
*/
type GetLoginFound struct {
}

// NewGetLoginFound creates GetLoginFound with default headers values
func NewGetLoginFound() *GetLoginFound {

	return &GetLoginFound{}
}

// WriteResponse to the client
func (o *GetLoginFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// GetLoginBadRequestCode is the HTTP code returned for type GetLoginBadRequest
const GetLoginBadRequestCode int = 400

/*GetLoginBadRequest Bad request

swagger:response getLoginBadRequest
*/
type GetLoginBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLoginBadRequest creates GetLoginBadRequest with default headers values
func NewGetLoginBadRequest() *GetLoginBadRequest {

	return &GetLoginBadRequest{}
}

// WithPayload adds the payload to the get login bad request response
func (o *GetLoginBadRequest) WithPayload(payload *models.Error) *GetLoginBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get login bad request response
func (o *GetLoginBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLoginUnauthorizedCode is the HTTP code returned for type GetLoginUnauthorized
const GetLoginUnauthorizedCode int = 401

/*GetLoginUnauthorized Unauthorized

swagger:response getLoginUnauthorized
*/
type GetLoginUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLoginUnauthorized creates GetLoginUnauthorized with default headers values
func NewGetLoginUnauthorized() *GetLoginUnauthorized {

	return &GetLoginUnauthorized{}
}

// WithPayload adds the payload to the get login unauthorized response
func (o *GetLoginUnauthorized) WithPayload(payload *models.Error) *GetLoginUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get login unauthorized response
func (o *GetLoginUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLoginInternalServerErrorCode is the HTTP code returned for type GetLoginInternalServerError
const GetLoginInternalServerErrorCode int = 500

/*GetLoginInternalServerError Internal Server Error

swagger:response getLoginInternalServerError
*/
type GetLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLoginInternalServerError creates GetLoginInternalServerError with default headers values
func NewGetLoginInternalServerError() *GetLoginInternalServerError {

	return &GetLoginInternalServerError{}
}

// WithPayload adds the payload to the get login internal server error response
func (o *GetLoginInternalServerError) WithPayload(payload *models.Error) *GetLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get login internal server error response
func (o *GetLoginInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
