// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/gmarcha/ent-goswagger-app/internal/goswagger/models"
)

// AddCalendarHandlerFunc turns a function with the right signature into a add calendar handler
type AddCalendarHandlerFunc func(AddCalendarParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddCalendarHandlerFunc) Handle(params AddCalendarParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddCalendarHandler interface for that can handle valid add calendar params
type AddCalendarHandler interface {
	Handle(AddCalendarParams, *models.Principal) middleware.Responder
}

// NewAddCalendar creates a new http.Handler for the add calendar operation
func NewAddCalendar(ctx *middleware.Context, handler AddCalendarHandler) *AddCalendar {
	return &AddCalendar{Context: ctx, Handler: handler}
}

/* AddCalendar swagger:route POST /users/{id}/role/calendar Role addCalendar

Add calendar

Add calendar role to a user.

*/
type AddCalendar struct {
	Context *middleware.Context
	Handler AddCalendarHandler
}

func (o *AddCalendar) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddCalendarParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
