// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gmarcha/ent-goswagger-app/internal/goswagger/models"
)

// DeleteMeNoContentCode is the HTTP code returned for type DeleteMeNoContent
const DeleteMeNoContentCode int = 204

/*DeleteMeNoContent No Content

swagger:response deleteMeNoContent
*/
type DeleteMeNoContent struct {
}

// NewDeleteMeNoContent creates DeleteMeNoContent with default headers values
func NewDeleteMeNoContent() *DeleteMeNoContent {

	return &DeleteMeNoContent{}
}

// WriteResponse to the client
func (o *DeleteMeNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteMeInternalServerErrorCode is the HTTP code returned for type DeleteMeInternalServerError
const DeleteMeInternalServerErrorCode int = 500

/*DeleteMeInternalServerError Internal Server Error

swagger:response deleteMeInternalServerError
*/
type DeleteMeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteMeInternalServerError creates DeleteMeInternalServerError with default headers values
func NewDeleteMeInternalServerError() *DeleteMeInternalServerError {

	return &DeleteMeInternalServerError{}
}

// WithPayload adds the payload to the delete me internal server error response
func (o *DeleteMeInternalServerError) WithPayload(payload *models.Error) *DeleteMeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete me internal server error response
func (o *DeleteMeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
