// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gmarcha/ent-goswagger-app/internal/ent"
	"github.com/gmarcha/ent-goswagger-app/internal/goswagger/models"
)

// ListUserRolesOKCode is the HTTP code returned for type ListUserRolesOK
const ListUserRolesOKCode int = 200

/*ListUserRolesOK OK

swagger:response listUserRolesOK
*/
type ListUserRolesOK struct {

	/*
	  In: Body
	*/
	Payload []*ent.Role `json:"body,omitempty"`
}

// NewListUserRolesOK creates ListUserRolesOK with default headers values
func NewListUserRolesOK() *ListUserRolesOK {

	return &ListUserRolesOK{}
}

// WithPayload adds the payload to the list user roles o k response
func (o *ListUserRolesOK) WithPayload(payload []*ent.Role) *ListUserRolesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user roles o k response
func (o *ListUserRolesOK) SetPayload(payload []*ent.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserRolesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*ent.Role, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListUserRolesBadRequestCode is the HTTP code returned for type ListUserRolesBadRequest
const ListUserRolesBadRequestCode int = 400

/*ListUserRolesBadRequest Bad request

swagger:response listUserRolesBadRequest
*/
type ListUserRolesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListUserRolesBadRequest creates ListUserRolesBadRequest with default headers values
func NewListUserRolesBadRequest() *ListUserRolesBadRequest {

	return &ListUserRolesBadRequest{}
}

// WithPayload adds the payload to the list user roles bad request response
func (o *ListUserRolesBadRequest) WithPayload(payload *models.Error) *ListUserRolesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user roles bad request response
func (o *ListUserRolesBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserRolesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUserRolesUnauthorizedCode is the HTTP code returned for type ListUserRolesUnauthorized
const ListUserRolesUnauthorizedCode int = 401

/*ListUserRolesUnauthorized Unauthorized

swagger:response listUserRolesUnauthorized
*/
type ListUserRolesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListUserRolesUnauthorized creates ListUserRolesUnauthorized with default headers values
func NewListUserRolesUnauthorized() *ListUserRolesUnauthorized {

	return &ListUserRolesUnauthorized{}
}

// WithPayload adds the payload to the list user roles unauthorized response
func (o *ListUserRolesUnauthorized) WithPayload(payload *models.Error) *ListUserRolesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user roles unauthorized response
func (o *ListUserRolesUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserRolesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUserRolesForbiddenCode is the HTTP code returned for type ListUserRolesForbidden
const ListUserRolesForbiddenCode int = 403

/*ListUserRolesForbidden Forbidden

swagger:response listUserRolesForbidden
*/
type ListUserRolesForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListUserRolesForbidden creates ListUserRolesForbidden with default headers values
func NewListUserRolesForbidden() *ListUserRolesForbidden {

	return &ListUserRolesForbidden{}
}

// WithPayload adds the payload to the list user roles forbidden response
func (o *ListUserRolesForbidden) WithPayload(payload *models.Error) *ListUserRolesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user roles forbidden response
func (o *ListUserRolesForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserRolesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUserRolesNotFoundCode is the HTTP code returned for type ListUserRolesNotFound
const ListUserRolesNotFoundCode int = 404

/*ListUserRolesNotFound Not Found

swagger:response listUserRolesNotFound
*/
type ListUserRolesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListUserRolesNotFound creates ListUserRolesNotFound with default headers values
func NewListUserRolesNotFound() *ListUserRolesNotFound {

	return &ListUserRolesNotFound{}
}

// WithPayload adds the payload to the list user roles not found response
func (o *ListUserRolesNotFound) WithPayload(payload *models.Error) *ListUserRolesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user roles not found response
func (o *ListUserRolesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserRolesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUserRolesInternalServerErrorCode is the HTTP code returned for type ListUserRolesInternalServerError
const ListUserRolesInternalServerErrorCode int = 500

/*ListUserRolesInternalServerError Internal Server Error

swagger:response listUserRolesInternalServerError
*/
type ListUserRolesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListUserRolesInternalServerError creates ListUserRolesInternalServerError with default headers values
func NewListUserRolesInternalServerError() *ListUserRolesInternalServerError {

	return &ListUserRolesInternalServerError{}
}

// WithPayload adds the payload to the list user roles internal server error response
func (o *ListUserRolesInternalServerError) WithPayload(payload *models.Error) *ListUserRolesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list user roles internal server error response
func (o *ListUserRolesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUserRolesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
