// Code generated by go-swagger; DO NOT EDIT.

package user_role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/gmarcha/ent-goswagger-app/internal/goswagger/models"
)

// RemoveAdminHandlerFunc turns a function with the right signature into a remove admin handler
type RemoveAdminHandlerFunc func(RemoveAdminParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveAdminHandlerFunc) Handle(params RemoveAdminParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// RemoveAdminHandler interface for that can handle valid remove admin params
type RemoveAdminHandler interface {
	Handle(RemoveAdminParams, *models.Principal) middleware.Responder
}

// NewRemoveAdmin creates a new http.Handler for the remove admin operation
func NewRemoveAdmin(ctx *middleware.Context, handler RemoveAdminHandler) *RemoveAdmin {
	return &RemoveAdmin{Context: ctx, Handler: handler}
}

/* RemoveAdmin swagger:route DELETE /users/{id}/role/admin UserRole removeAdmin

Remove admin

Remove admin role to a user.

*/
type RemoveAdmin struct {
	Context *middleware.Context
	Handler RemoveAdminHandler
}

func (o *RemoveAdmin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRemoveAdminParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
