// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gmarcha/ent-goswagger-app/internal/ent"
	"github.com/gmarcha/ent-goswagger-app/internal/goswagger/models"
)

// CreateEventCreatedCode is the HTTP code returned for type CreateEventCreated
const CreateEventCreatedCode int = 201

/*CreateEventCreated Created

swagger:response createEventCreated
*/
type CreateEventCreated struct {

	/*
	  In: Body
	*/
	Payload *ent.Event `json:"body,omitempty"`
}

// NewCreateEventCreated creates CreateEventCreated with default headers values
func NewCreateEventCreated() *CreateEventCreated {

	return &CreateEventCreated{}
}

// WithPayload adds the payload to the create event created response
func (o *CreateEventCreated) WithPayload(payload *ent.Event) *CreateEventCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create event created response
func (o *CreateEventCreated) SetPayload(payload *ent.Event) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateEventCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateEventBadRequestCode is the HTTP code returned for type CreateEventBadRequest
const CreateEventBadRequestCode int = 400

/*CreateEventBadRequest Bad request

swagger:response createEventBadRequest
*/
type CreateEventBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateEventBadRequest creates CreateEventBadRequest with default headers values
func NewCreateEventBadRequest() *CreateEventBadRequest {

	return &CreateEventBadRequest{}
}

// WithPayload adds the payload to the create event bad request response
func (o *CreateEventBadRequest) WithPayload(payload *models.Error) *CreateEventBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create event bad request response
func (o *CreateEventBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateEventBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateEventInternalServerErrorCode is the HTTP code returned for type CreateEventInternalServerError
const CreateEventInternalServerErrorCode int = 500

/*CreateEventInternalServerError Internal Server Error

swagger:response createEventInternalServerError
*/
type CreateEventInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateEventInternalServerError creates CreateEventInternalServerError with default headers values
func NewCreateEventInternalServerError() *CreateEventInternalServerError {

	return &CreateEventInternalServerError{}
}

// WithPayload adds the payload to the create event internal server error response
func (o *CreateEventInternalServerError) WithPayload(payload *models.Error) *CreateEventInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create event internal server error response
func (o *CreateEventInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
