name: CI

on:
  push:
    branches:
      - main
    # paths:
    #   - '**.go'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'

jobs:
  test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
      - name: build
        run: make ENV=ci
      - name: integration-test
        run: make test
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2 
