name: Swagger Validation

on:
  push:
    branches:
      - master
      - main
    tags:
      - v*
    paths:
      - 'config/specification.yaml'
  pull_request:
    paths:
      - 'config/specification.yaml'

jobs:
  validate:
    name: Validate Swagger specification
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository under workspace
        uses: actions/checkout@v2
      - name: Setup Go workspace
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.7'
      - name: Install dependencies
        run: |
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest
      - name: Perform Swagger specification validation
        run: make validate
      - name: Generate a markdown file from specification
        run: make markdown
      - name: Commit files
        id: commit
        run: |
          git add docs/swagger.md
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "::set-output name=push::false"
          else
            git config --local user.email "$(git log --format='%ae' HEAD^!)"
            git config --local user.name "$(git log --format='%an' HEAD^!)"
            git commit -m "update docs: auto-commit to update markdown from github-actions"
            echo "::set-output name=push::true"
          fi
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

